# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "programmer ∩ ml engineer ∩ mentor"
# other ideas for the above product, developer, leader
email:
description: >- # this means to ignore newlines until "baseurl:"
  Avishaan Singh Sethi "Avi", Chief Technology Officer,
  Machine Learning, Computer Vision, AI, Webapp, JavaScript, Python,
  React, Node.js, Health-tech, Healthcare, Deep Learning, Transfer Learning,
  Artificial Intelligence, Product Development, Agile, Lean Product Development, Webapp, PWA,
  React Native, Swift, Silicon Valley, ML, CTO, VP of Engineering, Head of Engineering, Director of Engineering
twitter_username: captainavi
github_username: avishaan
minimal_mistakes_skin: mint
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : 'Avishaan Singh Sethi "Avi"'
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "👨‍💻 fmr CTO of Babynoggin <br /> 🤖 ML/AI engineer <br /> 🧬 health-tech product dev <br /> 👨‍🚀 fmr NASA engineer <br /> 💃 salsa dancer"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://avishaan.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/captainavishaan"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/avishaan"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/captainavi"
    - label: "Meet with Me"
      icon: "fab fa-fw fa-discourse"
      url: "https://avishaan.com/schedule/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/captainavishaan"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/codehatcher"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/captainavi"
    - label: "Meet with Me"
      icon: "fab fa-fw fa-discourse"
      url: "https://avishaan.com/schedule/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-24354993-1"
    anonymize_ip: false # default
